"""add_new_models_retention_roles_folders_chat

Revision ID: 09dc9796c8b9
Revises: 99600e9f69d6
Create Date: 2025-12-12 09:25:35.462792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09dc9796c8b9'
down_revision: Union[str, None] = '99600e9f69d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retention_policies',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('disposition', sa.String(length=50), nullable=False),
    sa.Column('legal_hold', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retention_policies_id'), 'retention_policies', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('feedback', sa.JSON(), nullable=True),
    sa.Column('handoff_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['document_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_table('document_group_tags',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['document_groups.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'tag_id')
    )
    op.create_table('folders',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_folders_id'), 'folders', ['id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('document_group_folders',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['document_groups.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'folder_id')
    )
    op.create_table('document_group_documents',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['document_groups.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'document_id')
    )
    op.create_table('comments',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('position', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.add_column('devices', sa.Column('allowed_users', sa.JSON(), nullable=True))
    op.add_column('devices', sa.Column('allowed_groups', sa.JSON(), nullable=True))
    op.add_column('document_groups', sa.Column('owners', sa.JSON(), nullable=True))
    op.add_column('document_groups', sa.Column('allowed_roles', sa.JSON(), nullable=True))
    op.add_column('document_groups', sa.Column('allowed_users', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'documents', 'retention_policies', ['retention_policy_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'folders', ['folder_id'], ['id'])
    op.add_column('shares', sa.Column('share_token', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'shares', ['share_token'])
    op.add_column('users', sa.Column('locale', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('time_zone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'time_zone')
    op.drop_column('users', 'locale')
    op.drop_constraint(None, 'shares', type_='unique')
    op.drop_column('shares', 'share_token')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('document_groups', 'allowed_users')
    op.drop_column('document_groups', 'allowed_roles')
    op.drop_column('document_groups', 'owners')
    op.drop_column('devices', 'allowed_groups')
    op.drop_column('devices', 'allowed_users')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_table('document_group_documents')
    op.drop_table('document_group_folders')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_folders_id'), table_name='folders')
    op.drop_table('folders')
    op.drop_table('document_group_tags')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_retention_policies_id'), table_name='retention_policies')
    op.drop_table('retention_policies')
    # ### end Alembic commands ###






