"""add_is_maintainer_to_users

Revision ID: 498e59384a71
Revises: 09dc9796c8b9
Create Date: 2025-12-12 13:51:03.160779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '498e59384a71'
down_revision: Union[str, None] = '09dc9796c8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with default value first to handle existing records
    op.add_column('users', sa.Column('is_maintainer', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_maintainer')
    # ### end Alembic commands ###






