"""add_token_tracking_to_chat_sessions

Revision ID: a1b2c3d4e5f6
Revises: 498e59384a71
Create Date: 2025-01-15 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '498e59384a71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with default value 0 to handle existing records
    op.add_column('chat_sessions', sa.Column('token_in_total', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('chat_sessions', sa.Column('token_out_total', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'token_out_total')
    op.drop_column('chat_sessions', 'token_in_total')
    # ### end Alembic commands ###

